name: End-to-end tests
on: push
jobs:
  selenium-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Selenium tests with pytest
        run: |
          pytest
