name: End-to-end tests
on: push
jobs:
  selenium-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'


      - name: Run Selenium tests with pytest
        run: |
          pytest
